@startuml

skinparam backgroundColor white
skinparam handwritten false

actor "系统管理员" as Admin
actor "教材管理员" as TAdmin
actor "外部学习辅助设备" as Dev
actor "可编程设备" as Pro
actor "显示设备" as Disp

usecase "投屏显示" as UC08
usecase "硬件代码验证" as UC09

TAdmin --|> Admin
Pro --|> Dev
Disp --|> Dev

Disp --> UC08
Pro --> UC09

@enduml